service: serverless-sample

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-west-1
  environment:
    USER_TABLE: ${self:service}-user

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamo:PutItem"
        - "dynamo:GetItem"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:dynamo:::"

package:
  individually: true
  include:
    - node_modules/co
    - node_modules/bluebird
    - node_modules/chance

functions:
  registerUser:
    handler: api/users/post.handle
    events:
      - http:
          path: users
          method: post

#    Define function environment variables here
#    environment:
#      variable2: value2

resources:
Resources: 
  userTable: 
    Type: "AWS::DynamoDB::Table"
    Properties: 
      AttributeDefinitions: 
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "Album"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: ${self:provide.environment.USER_TABLE}